# Generated by Django 2.1.1 on 2019-06-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20190628_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duaapprovals',
            name='user',
        ),
        migrations.DeleteModel(
            name='DuaApprovals',
        ),
    ]
