# Generated by Django 2.1.10 on 2019-08-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_status'),
        ('user_manager', '0003_auto_20190630_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dua_good_until_date',
        ),
        migrations.AddField(
            model_name='user',
            name='default_work_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.WorkUnit'),
        ),
    ]
