# Generated by Django 2.1.7 on 2019-10-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20190816_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
